export const CREATE_NUMBER_SET = 'CREATE_NUMBER_SET'

export const SET_NUMBER_RANDOM = 'SET_NUMBER_RANDOM'

export const SET_NUMBER_REAL = 'SET_NUMBER_REAL'

export const SET_HAS_TEST_STARTED = 'SET_HAS_TEST_STARTED'

export const SET_NEXT_STAGE = 'SET_NEXT_STAGE'

export const SET_EMAIL = 'SET_EMAIL'